# Стадия сборки
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY *.sln .
COPY FileProcessingApp/*.csproj ./FileProcessingApp/
RUN dotnet restore

COPY FileProcessingApp/. ./FileProcessingApp/
WORKDIR /src/FileProcessingApp
RUN dotnet publish -c Release -o /app/publish

# Стадия выполнения
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "FileProcessingApp.dll"]